<?php

$country_list = array(
	array("name" => "Afghanistan", "code" => "AF"),
	array("name" => "Albania", "code" => "AL"),
	array("name" => "Algeria", "code" => "DZ"),
	array("name" => "Andorra", "code" => "AD"),
	array("name" => "Angola", "code" => "AO"),
	array("name" => "Antigua and Barbuda", "code" => "AG"),
	array("name" => "Argentina", "code" => "AR"),
	array("name" => "Armenia", "code" => "AM"),
	array("name" => "Australia", "code" => "AU"),
	array("name" => "Austria", "code" => "AT"),
	array("name" => "Azerbaijan", "code" => "AZ"),
	array("name" => "Bahamas, The", "code" => "BS"),
	array("name" => "Bahrain", "code" => "BH"),
	array("name" => "Bangladesh", "code" => "BD"),
	array("name" => "Barbados", "code" => "BB"),
	array("name" => "Belarus", "code" => "BY"),
	array("name" => "Belgium", "code" => "BE"),
	array("name" => "Belize", "code" => "BZ"),
	array("name" => "Benin", "code" => "BJ"),
	array("name" => "Bhutan", "code" => "BT"),
	array("name" => "Bolivia", "code" => "BO"),
	array("name" => "Bosnia and Herzegovina", "code" => "BA"),
	array("name" => "Botswana", "code" => "BW"),
	array("name" => "Brazil", "code" => "BR"),
	array("name" => "Brunei", "code" => "BN"),
	array("name" => "Bulgaria", "code" => "BG"),
	array("name" => "Burkina Faso", "code" => "BF"),
	array("name" => "Burundi", "code" => "BI"),
	array("name" => "Cambodia", "code" => "KH"),
	array("name" => "Cameroon", "code" => "CM"),
	array("name" => "Canada", "code" => "CA"),
	array("name" => "Cape Verde", "code" => "CV"),
	array("name" => "Central African Republic", "code" => "CF"),
	array("name" => "Chad", "code" => "TD"),
	array("name" => "Chile", "code" => "CL"),
	array("name" => "China, People's Republic of", "code" => "CN"),
	array("name" => "Colombia", "code" => "CO"),
	array("name" => "Comoros", "code" => "KM"),
	array("name" => "Congo, Democratic Republic of the", "code" => "CD"),
	array("name" => "Congo, Republic of the", "code" => "CG"),
	array("name" => "Costa Rica", "code" => "CR"),
	array("name" => "Cote d'Ivoire (Ivory Coast)", "code" => "CI"),
	array("name" => "Croatia", "code" => "HR"),
	array("name" => "Cuba", "code" => "CU"),
	array("name" => "Cyprus", "code" => "CY"),
	array("name" => "Czech Republic", "code" => "CZ"),
	array("name" => "Denmark", "code" => "DK"),
	array("name" => "Djibouti", "code" => "DJ"),
	array("name" => "Dominica", "code" => "DM"),
	array("name" => "Dominican Republic", "code" => "DO"),
	array("name" => "Ecuador", "code" => "EC"),
	array("name" => "Egypt", "code" => "EG"),
	array("name" => "El Salvador", "code" => "SV"),
	array("name" => "Equatorial Guinea", "code" => "GQ"),
	array("name" => "Eritrea", "code" => "ER"),
	array("name" => "Estonia", "code" => "EE"),
	array("name" => "Ethiopia", "code" => "ET"),
	array("name" => "Fiji", "code" => "FJ"),
	array("name" => "Finland", "code" => "FI"),
	array("name" => "France", "code" => "FR"),
	array("name" => "Gabon", "code" => "GA"),
	array("name" => "Gambia, The", "code" => "GM"),
	array("name" => "Georgia", "code" => "GE"),
	array("name" => "Germany", "code" => "DE"),
	array("name" => "Ghana", "code" => "GH"),
	array("name" => "Greece", "code" => "GR"),
	array("name" => "Grenada", "code" => "GD"),
	array("name" => "Guatemala", "code" => "GT"),
	array("name" => "Guinea", "code" => "GN"),
	array("name" => "Guinea-Bissau", "code" => "GW"),
	array("name" => "Guyana", "code" => "GY"),
	array("name" => "Haiti", "code" => "HT"),
	array("name" => "Honduras", "code" => "HN"),
	array("name" => "Hungary", "code" => "HU"),
	array("name" => "Iceland", "code" => "IS"),
	array("name" => "India", "code" => "IN"),
	array("name" => "Indonesia", "code" => "ID"),
	array("name" => "Iran", "code" => "IR"),
	array("name" => "Iraq", "code" => "IQ"),
	array("name" => "Ireland", "code" => "IE"),
	array("name" => "Israel", "code" => "IL"),
	array("name" => "Italy", "code" => "IT"),
	array("name" => "Jamaica", "code" => "JM"),
	array("name" => "Japan", "code" => "JP"),
	array("name" => "Jordan", "code" => "JO"),
	array("name" => "Kazakhstan", "code" => "KZ"),
	array("name" => "Kenya", "code" => "KE"),
	array("name" => "Kiribati", "code" => "KI"),
	array("name" => "Korea, North", "code" => "KP"),
	array("name" => "Korea, South", "code" => "KR"),
	array("name" => "Kuwait", "code" => "KW"),
	array("name" => "Kyrgyzstan", "code" => "KG"),
	array("name" => "Laos", "code" => "LA"),
	array("name" => "Latvia", "code" => "LV"),
	array("name" => "Lebanon", "code" => "LB"),
	array("name" => "Lesotho", "code" => "LS"),
	array("name" => "Liberia", "code" => "LR"),
	array("name" => "Libya", "code" => "LY"),
	array("name" => "Liechtenstein", "code" => "LI"),
	array("name" => "Lithuania", "code" => "LT"),
	array("name" => "Luxembourg", "code" => "LU"),
	array("name" => "Macedonia", "code" => "MK"),
	array("name" => "Madagascar", "code" => "MG"),
	array("name" => "Malawi", "code" => "MW"),
	array("name" => "Malaysia", "code" => "MY"),
	array("name" => "Maldives", "code" => "MV"),
	array("name" => "Mali", "code" => "ML"),
	array("name" => "Malta", "code" => "MT"),
	array("name" => "Marshall Islands", "code" => "MH"),
	array("name" => "Mauritania", "code" => "MR"),
	array("name" => "Mauritius", "code" => "MU"),
	array("name" => "Mexico", "code" => "MX"),
	array("name" => "Micronesia", "code" => "FM"),
	array("name" => "Moldova", "code" => "MD"),
	array("name" => "Monaco", "code" => "MC"),
	array("name" => "Mongolia", "code" => "MN"),
	array("name" => "Montenegro", "code" => "ME"),
	array("name" => "Morocco", "code" => "MA"),
	array("name" => "Mozambique", "code" => "MZ"),
	array("name" => "Myanmar (Burma)", "code" => "MM"),
	array("name" => "Namibia", "code" => "NA"),
	array("name" => "Nauru", "code" => "NR"),
	array("name" => "Nepal", "code" => "NP"),
	array("name" => "Netherlands", "code" => "NL"),
	array("name" => "New Zealand", "code" => "NZ"),
	array("name" => "Nicaragua", "code" => "NI"),
	array("name" => "Niger", "code" => "NE"),
	array("name" => "Nigeria", "code" => "NG"),
	array("name" => "Norway", "code" => "NO"),
	array("name" => "Oman", "code" => "OM"),
	array("name" => "Pakistan", "code" => "PK"),
	array("name" => "Palau", "code" => "PW"),
	array("name" => "Panama", "code" => "PA"),
	array("name" => "Papua New Guinea", "code" => "PG"),
	array("name" => "Paraguay", "code" => "PY"),
	array("name" => "Peru", "code" => "PE"),
	array("name" => "Philippines", "code" => "PH"),
	array("name" => "Poland", "code" => "PL"),
	array("name" => "Portugal", "code" => "PT"),
	array("name" => "Qatar", "code" => "QA"),
	array("name" => "Romania", "code" => "RO"),
	array("name" => "Russia", "code" => "RU"),
	array("name" => "Rwanda", "code" => "RW"),
	array("name" => "Saint Kitts and Nevis", "code" => "KN"),
	array("name" => "Saint Lucia", "code" => "LC"),
	array("name" => "Saint Vincent and the Grenadines", "code" => "VC"),
	array("name" => "Samoa", "code" => "WS"),
	array("name" => "San Marino", "code" => "SM"),
	array("name" => "Sao Tome and Principe", "code" => "ST"),
	array("name" => "Saudi Arabia", "code" => "SA"),
	array("name" => "Senegal", "code" => "SN"),
	array("name" => "Serbia", "code" => "RS"),
	array("name" => "Seychelles", "code" => "SC"),
	array("name" => "Sierra Leone", "code" => "SL"),
	array("name" => "Singapore", "code" => "SG"),
	array("name" => "Slovakia", "code" => "SK"),
	array("name" => "Slovenia", "code" => "SI"),
	array("name" => "Solomon Islands", "code" => "SB"),
	array("name" => "Somalia", "code" => "SO"),
	array("name" => "South Africa", "code" => "ZA"),
	array("name" => "Spain", "code" => "ES"),
	array("name" => "Sri Lanka", "code" => "LK"),
	array("name" => "Sudan", "code" => "SD"),
	array("name" => "Suriname", "code" => "SR"),
	array("name" => "Swaziland", "code" => "SZ"),
	array("name" => "Sweden", "code" => "SE"),
	array("name" => "Switzerland", "code" => "CH"),
	array("name" => "Syria", "code" => "SY"),
	array("name" => "Tajikistan", "code" => "TJ"),
	array("name" => "Tanzania", "code" => "TZ"),
	array("name" => "Thailand", "code" => "TH"),
	array("name" => "Timor-Leste (East Timor)", "code" => "TL"),
	array("name" => "Togo", "code" => "TG"),
	array("name" => "Tonga", "code" => "TO"),
	array("name" => "Trinidad and Tobago", "code" => "TT"),
	array("name" => "Tunisia", "code" => "TN"),
	array("name" => "Turkey", "code" => "TR"),
	array("name" => "Turkmenistan", "code" => "TM"),
	array("name" => "Tuvalu", "code" => "TV"),
	array("name" => "Uganda", "code" => "UG"),
	array("name" => "Ukraine", "code" => "UA"),
	array("name" => "United Arab Emirates", "code" => "AE"),
	array("name" => "United Kingdom", "code" => "GB"),
	array("name" => "United States", "code" => "US"),
	array("name" => "Uruguay", "code" => "UY"),
	array("name" => "Uzbekistan", "code" => "UZ"),
	array("name" => "Vanuatu", "code" => "VU"),
	array("name" => "Vatican City", "code" => "VA"),
	array("name" => "Venezuela", "code" => "VE"),
	array("name" => "Vietnam", "code" => "VN"),
	array("name" => "Yemen", "code" => "YE"),
	array("name" => "Zambia", "code" => "ZM"),
	array("name" => "Zimbabwe", "code" => "ZW"),
	array("name" => "Abkhazia", "code" => "GE"),
	array("name" => "China, Republic of (Taiwan)", "code" => "TW"),
	array("name" => "Nagorno-Karabakh", "code" => "AZ"),
	array("name" => "Northern Cyprus", "code" => "CY"),
	array("name" => "Pridnestrovie (Transnistria)", "code" => "MD"),
	array("name" => "Somaliland", "code" => "SO"),
	array("name" => "South Ossetia", "code" => "GE"),
	array("name" => "Ashmore and Cartier Islands", "code" => "AU"),
	array("name" => "Christmas Island", "code" => "CX"),
	array("name" => "Cocos (Keeling) Islands", "code" => "CC"),
	array("name" => "Coral Sea Islands", "code" => "AU"),
	array("name" => "Heard Island and McDonald Islands", "code" => "HM"),
	array("name" => "Norfolk Island", "code" => "NF"),
	array("name" => "New Caledonia", "code" => "NC"),
	array("name" => "French Polynesia", "code" => "PF"),
	array("name" => "Mayotte", "code" => "YT"),
	array("name" => "Saint Barthelemy", "code" => "GP"),
	array("name" => "Saint Martin", "code" => "GP"),
	array("name" => "Saint Pierre and Miquelon", "code" => "PM"),
	array("name" => "Wallis and Futuna", "code" => "WF"),
	array("name" => "French Southern and Antarctic Lands", "code" => "TF"),
	array("name" => "Clipperton Island", "code" => "PF"),
	array("name" => "Bouvet Island", "code" => "BV"),
	array("name" => "Cook Islands", "code" => "CK"),
	array("name" => "Niue", "code" => "NU"),
	array("name" => "Tokelau", "code" => "TK"),
	array("name" => "Guernsey", "code" => "GG"),
	array("name" => "Isle of Man", "code" => "IM"),
	array("name" => "Jersey", "code" => "JE"),
	array("name" => "Anguilla", "code" => "AI"),
	array("name" => "Bermuda", "code" => "BM"),
	array("name" => "British Indian Ocean Territory", "code" => "IO"),
	array("name" => "British Virgin Islands", "code" => "VG"),
	array("name" => "Cayman Islands", "code" => "KY"),
	array("name" => "Falkland Islands (Islas Malvinas)", "code" => "FK"),
	array("name" => "Gibraltar", "code" => "GI"),
	array("name" => "Montserrat", "code" => "MS"),
	array("name" => "Pitcairn Islands", "code" => "PN"),
	array("name" => "Saint Helena", "code" => "SH"),
	array("name" => "South Georgia & South Sandwich Islands", "code" => "GS"),
	array("name" => "Turks and Caicos Islands", "code" => "TC"),
	array("name" => "Northern Mariana Islands", "code" => "MP"),
	array("name" => "Puerto Rico", "code" => "PR"),
	array("name" => "American Samoa", "code" => "AS"),
	array("name" => "Baker Island", "code" => "UM"),
	array("name" => "Guam", "code" => "GU"),
	array("name" => "Howland Island", "code" => "UM"),
	array("name" => "Jarvis Island", "code" => "UM"),
	array("name" => "Johnston Atoll", "code" => "UM"),
	array("name" => "Kingman Reef", "code" => "UM"),
	array("name" => "Midway Islands", "code" => "UM"),
	array("name" => "Navassa Island", "code" => "UM"),
	array("name" => "Palmyra Atoll", "code" => "UM"),
	array("name" => "U.S. Virgin Islands", "code" => "VI"),
	array("name" => "Wake Island", "code" => "UM"),
	array("name" => "Hong Kong", "code" => "HK"),
	array("name" => "Macau", "code" => "MO"),
	array("name" => "Faroe Islands", "code" => "FO"),
	array("name" => "Greenland", "code" => "GL"),
	array("name" => "French Guiana", "code" => "GF"),
	array("name" => "Guadeloupe", "code" => "GP"),
	array("name" => "Martinique", "code" => "MQ"),
	array("name" => "Reunion", "code" => "RE"),
	array("name" => "Aland", "code" => "AX"),
	array("name" => "Aruba", "code" => "AW"),
	array("name" => "Netherlands Antilles", "code" => "AN"),
	array("name" => "Svalbard", "code" => "SJ"),
	array("name" => "Ascension", "code" => "AC"),
	array("name" => "Tristan da Cunha", "code" => "TA"),
	array("name" => "Australian Antarctic Territory", "code" => "AQ"),
	array("name" => "Ross Dependency", "code" => "AQ"),
	array("name" => "Peter I Island", "code" => "AQ"),
	array("name" => "Queen Maud Land", "code" => "AQ"),
	array("name" => "British Antarctic Territory", "code" => "AQ")
);